# Generated by Django 5.2.6 on 2026-02-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['level']},
        ),
        migrations.AddField(
            model_name='role',
            name='level',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('moderateur', 'Modérateur'), ('contributeur', 'Contributeur'), ('utilisateur', 'Utilisateur')], max_length=20, unique=True),
        ),
    ]
